
# ---
# spring:
#   config.activate.on-profile: default
#   sql.init.platform: h2
# cds:
#   data-source.auto-config.enabled: false
---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
cds:
  data-source:             #  inside cds
    auto-config:
      enabled: true

  security:
    authentication:
      authConfig:
        enabled: false

  health:                  #  inside cds
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true